### ISSUE TITLE
UserPoolDomain] is missing required property: domain

### ISSUE THREAD

**Issue by dcabib** [awesome-cdk/cognito-google-federation-example#1]
I am trying to deploy the CDK stack and this error has been raising:

Error: CognitoGoogleFederationExperiment/UserPool/default/Resource [AWS::Cognito::UserPoolDomain] is missing required property: domain
    at Object.requireProperty (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/node_modules/aws-cdk-lib/core/lib/runtime.js:4:2814)
    at new CfnUserPoolDomain (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/node_modules/aws-cdk-lib/aws-cognito/lib/cognito.generated.js:1:100676)
    at new UserPoolDomain (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/node_modules/aws-cdk-lib/aws-cognito/lib/user-pool-domain.js:1:1187)
    at UserPool.addDomain (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/node_modules/aws-cdk-lib/aws-cognito/lib/user-pool.js:1:3174)
    at new CognitoGoogleFederationExperiment (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/lib/CognitoGoogleFederationExperiment.ts:37:41)
    at Object.<anonymous> (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/bin/aws-cdk-cognito-test.ts:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ec2-user/environment/tmp-cognito/cognito-google-federation-example/node_modules/ts-node/src/index.ts:1600:12)

**Comment by metuuu** [comment]
You get the error if you set domain prefix value as the cognitoDomain option.
`userPool.addDomain("id", { cognitoDomain: "domain-prefix" })`

**cognitoDomain** option is an object that contains **domainPrefix** property.
`userPool.addDomain("id", { cognitoDomain: { domainPrefix: "domain-prefix" }})`
